-- V6:表名/列名统一小写蛇形(PG 标准),去掉全项目双引号依赖。
-- 迁移只跑一次;两库(inventory/inventory_test)都要执行。
-- 列清单来源:information_schema.columns 实测(2026-09-11)。

BEGIN;

-- ===== 1. 表名 =====
ALTER TABLE "Batch" RENAME TO batch;
ALTER TABLE "Customer" RENAME TO customer;
ALTER TABLE "Dict" RENAME TO dict;
ALTER TABLE "DictType" RENAME TO dict_type;
ALTER TABLE "InboundDoc" RENAME TO inbound_doc;
ALTER TABLE "InboundDocItem" RENAME TO inbound_doc_item;
ALTER TABLE "Item" RENAME TO item;
ALTER TABLE "Location" RENAME TO location;
ALTER TABLE "OutboundDoc" RENAME TO outbound_doc;
ALTER TABLE "OutboundDocItem" RENAME TO outbound_doc_item;
ALTER TABLE "PurchaseOrder" RENAME TO purchase_order;
ALTER TABLE "PurchaseOrderItem" RENAME TO purchase_order_item;
ALTER TABLE "SalesOrder" RENAME TO sales_order;
ALTER TABLE "SalesOrderItem" RENAME TO sales_order_item;
ALTER TABLE "Serial" RENAME TO serial;
ALTER TABLE "Stock" RENAME TO stock;
ALTER TABLE "StockAdjustDoc" RENAME TO stock_adjust_doc;
ALTER TABLE "StockAdjustDocItem" RENAME TO stock_adjust_doc_item;
ALTER TABLE "StockTransaction" RENAME TO stock_transaction;
ALTER TABLE "StocktakeDoc" RENAME TO stocktake_doc;
ALTER TABLE "StocktakeDocItem" RENAME TO stocktake_doc_item;
ALTER TABLE "Supplier" RENAME TO supplier;
ALTER TABLE "TransferDoc" RENAME TO transfer_doc;
ALTER TABLE "TransferDocItem" RENAME TO transfer_doc_item;
ALTER TABLE "User" RENAME TO sys_user;
ALTER TABLE "Warehouse" RENAME TO warehouse;

-- ===== 2. 列名 =====
ALTER TABLE batch RENAME COLUMN "itemId" TO item_id;
ALTER TABLE batch RENAME COLUMN "batchNo" TO batch_no;
ALTER TABLE batch RENAME COLUMN "productionDate" TO production_date;
ALTER TABLE batch RENAME COLUMN "expiryDate" TO expiry_date;
ALTER TABLE customer RENAME COLUMN "customerCode" TO customer_code;
ALTER TABLE customer RENAME COLUMN "customerName" TO customer_name;
ALTER TABLE customer RENAME COLUMN "taxNo" TO tax_no;
ALTER TABLE customer RENAME COLUMN "defaultTaxRate" TO default_tax_rate;
ALTER TABLE customer RENAME COLUMN "settleMethod" TO settle_method;
ALTER TABLE customer RENAME COLUMN "payTermDays" TO pay_term_days;
ALTER TABLE customer RENAME COLUMN "createdAt" TO created_at;
ALTER TABLE customer RENAME COLUMN "updatedAt" TO updated_at;
ALTER TABLE dict RENAME COLUMN "dictType" TO dict_type;
ALTER TABLE dict RENAME COLUMN "dictKey" TO dict_key;
ALTER TABLE dict RENAME COLUMN "dictLabel" TO dict_label;
ALTER TABLE dict RENAME COLUMN "sortOrder" TO sort_order;
ALTER TABLE dict RENAME COLUMN "createdAt" TO created_at;
ALTER TABLE dict RENAME COLUMN "updatedAt" TO updated_at;
ALTER TABLE dict_type RENAME COLUMN "typeCode" TO type_code;
ALTER TABLE dict_type RENAME COLUMN "typeName" TO type_name;
ALTER TABLE dict_type RENAME COLUMN "createdAt" TO created_at;
ALTER TABLE dict_type RENAME COLUMN "updatedAt" TO updated_at;
ALTER TABLE inbound_doc RENAME COLUMN "docNo" TO doc_no;
ALTER TABLE inbound_doc RENAME COLUMN "warehouseId" TO warehouse_id;
ALTER TABLE inbound_doc RENAME COLUMN "createdAt" TO created_at;
ALTER TABLE inbound_doc RENAME COLUMN "refType" TO ref_type;
ALTER TABLE inbound_doc RENAME COLUMN "refDocId" TO ref_doc_id;
ALTER TABLE inbound_doc RENAME COLUMN "docDate" TO doc_date;
ALTER TABLE inbound_doc RENAME COLUMN "updatedAt" TO updated_at;
ALTER TABLE inbound_doc_item RENAME COLUMN "docId" TO doc_id;
ALTER TABLE inbound_doc_item RENAME COLUMN "itemId" TO item_id;
ALTER TABLE inbound_doc_item RENAME COLUMN "batchId" TO batch_id;
ALTER TABLE inbound_doc_item RENAME COLUMN "locationId" TO location_id;
ALTER TABLE inbound_doc_item RENAME COLUMN "serialNos" TO serial_nos;
ALTER TABLE inbound_doc_item RENAME COLUMN "unitPrice" TO unit_price;
ALTER TABLE inbound_doc_item RENAME COLUMN "taxRate" TO tax_rate;
ALTER TABLE inbound_doc_item RENAME COLUMN "batchNo" TO batch_no;
ALTER TABLE inbound_doc_item RENAME COLUMN "productionDate" TO production_date;
ALTER TABLE inbound_doc_item RENAME COLUMN "expiryDate" TO expiry_date;
ALTER TABLE inbound_doc_item RENAME COLUMN "refLineId" TO ref_line_id;
ALTER TABLE item RENAME COLUMN "itemCode" TO item_code;
ALTER TABLE item RENAME COLUMN "itemName" TO item_name;
ALTER TABLE item RENAME COLUMN "createdAt" TO created_at;
ALTER TABLE item RENAME COLUMN "minStock" TO min_stock;
ALTER TABLE item RENAME COLUMN "defaultTaxRate" TO default_tax_rate;
ALTER TABLE item RENAME COLUMN "updatedAt" TO updated_at;
ALTER TABLE location RENAME COLUMN "warehouseId" TO warehouse_id;
ALTER TABLE location RENAME COLUMN "locationCode" TO location_code;
ALTER TABLE location RENAME COLUMN "locationName" TO location_name;
ALTER TABLE location RENAME COLUMN "createdAt" TO created_at;
ALTER TABLE location RENAME COLUMN "updatedAt" TO updated_at;
ALTER TABLE outbound_doc RENAME COLUMN "docNo" TO doc_no;
ALTER TABLE outbound_doc RENAME COLUMN "warehouseId" TO warehouse_id;
ALTER TABLE outbound_doc RENAME COLUMN "createdAt" TO created_at;
ALTER TABLE outbound_doc RENAME COLUMN "refType" TO ref_type;
ALTER TABLE outbound_doc RENAME COLUMN "refDocId" TO ref_doc_id;
ALTER TABLE outbound_doc RENAME COLUMN "docDate" TO doc_date;
ALTER TABLE outbound_doc RENAME COLUMN "updatedAt" TO updated_at;
ALTER TABLE outbound_doc_item RENAME COLUMN "docId" TO doc_id;
ALTER TABLE outbound_doc_item RENAME COLUMN "itemId" TO item_id;
ALTER TABLE outbound_doc_item RENAME COLUMN "batchId" TO batch_id;
ALTER TABLE outbound_doc_item RENAME COLUMN "locationId" TO location_id;
ALTER TABLE outbound_doc_item RENAME COLUMN "serialNos" TO serial_nos;
ALTER TABLE outbound_doc_item RENAME COLUMN "unitPrice" TO unit_price;
ALTER TABLE outbound_doc_item RENAME COLUMN "refLineId" TO ref_line_id;
ALTER TABLE purchase_order RENAME COLUMN "docNo" TO doc_no;
ALTER TABLE purchase_order RENAME COLUMN "docDate" TO doc_date;
ALTER TABLE purchase_order RENAME COLUMN "supplierId" TO supplier_id;
ALTER TABLE purchase_order RENAME COLUMN "buyerId" TO buyer_id;
ALTER TABLE purchase_order RENAME COLUMN "allowOverReceiptRate" TO allow_over_receipt_rate;
ALTER TABLE purchase_order RENAME COLUMN "totalAmount" TO total_amount;
ALTER TABLE purchase_order RENAME COLUMN "totalTaxAmount" TO total_tax_amount;
ALTER TABLE purchase_order RENAME COLUMN "totalTaxInclusive" TO total_tax_inclusive;
ALTER TABLE purchase_order RENAME COLUMN "createdAt" TO created_at;
ALTER TABLE purchase_order RENAME COLUMN "updatedAt" TO updated_at;
ALTER TABLE purchase_order RENAME COLUMN "approvedAt" TO approved_at;
ALTER TABLE purchase_order RENAME COLUMN "rejectReason" TO reject_reason;
ALTER TABLE purchase_order_item RENAME COLUMN "orderId" TO order_id;
ALTER TABLE purchase_order_item RENAME COLUMN "lineNo" TO line_no;
ALTER TABLE purchase_order_item RENAME COLUMN "itemId" TO item_id;
ALTER TABLE purchase_order_item RENAME COLUMN "specSnapshot" TO spec_snapshot;
ALTER TABLE purchase_order_item RENAME COLUMN "orderedQty" TO ordered_qty;
ALTER TABLE purchase_order_item RENAME COLUMN "arrivedQty" TO arrived_qty;
ALTER TABLE purchase_order_item RENAME COLUMN "expectedDeliveryDate" TO expected_delivery_date;
ALTER TABLE purchase_order_item RENAME COLUMN "unitPrice" TO unit_price;
ALTER TABLE purchase_order_item RENAME COLUMN "taxRate" TO tax_rate;
ALTER TABLE purchase_order_item RENAME COLUMN "taxAmount" TO tax_amount;
ALTER TABLE purchase_order_item RENAME COLUMN "taxInclusiveTotal" TO tax_inclusive_total;
ALTER TABLE purchase_order_item RENAME COLUMN "lineRemark" TO line_remark;
ALTER TABLE sales_order RENAME COLUMN "docNo" TO doc_no;
ALTER TABLE sales_order RENAME COLUMN "docDate" TO doc_date;
ALTER TABLE sales_order RENAME COLUMN "customerId" TO customer_id;
ALTER TABLE sales_order RENAME COLUMN "salespersonId" TO salesperson_id;
ALTER TABLE sales_order RENAME COLUMN "warehouseId" TO warehouse_id;
ALTER TABLE sales_order RENAME COLUMN "totalAmount" TO total_amount;
ALTER TABLE sales_order RENAME COLUMN "totalTaxAmount" TO total_tax_amount;
ALTER TABLE sales_order RENAME COLUMN "totalTaxInclusive" TO total_tax_inclusive;
ALTER TABLE sales_order RENAME COLUMN "createdAt" TO created_at;
ALTER TABLE sales_order RENAME COLUMN "updatedAt" TO updated_at;
ALTER TABLE sales_order RENAME COLUMN "approvedAt" TO approved_at;
ALTER TABLE sales_order RENAME COLUMN "rejectReason" TO reject_reason;
ALTER TABLE sales_order_item RENAME COLUMN "orderId" TO order_id;
ALTER TABLE sales_order_item RENAME COLUMN "lineNo" TO line_no;
ALTER TABLE sales_order_item RENAME COLUMN "itemId" TO item_id;
ALTER TABLE sales_order_item RENAME COLUMN "specSnapshot" TO spec_snapshot;
ALTER TABLE sales_order_item RENAME COLUMN "orderedQty" TO ordered_qty;
ALTER TABLE sales_order_item RENAME COLUMN "shippedQty" TO shipped_qty;
ALTER TABLE sales_order_item RENAME COLUMN "customerDeliveryDate" TO customer_delivery_date;
ALTER TABLE sales_order_item RENAME COLUMN "unitPrice" TO unit_price;
ALTER TABLE sales_order_item RENAME COLUMN "taxRate" TO tax_rate;
ALTER TABLE sales_order_item RENAME COLUMN "taxAmount" TO tax_amount;
ALTER TABLE sales_order_item RENAME COLUMN "taxInclusiveTotal" TO tax_inclusive_total;
ALTER TABLE sales_order_item RENAME COLUMN "lineRemark" TO line_remark;
ALTER TABLE serial RENAME COLUMN "itemId" TO item_id;
ALTER TABLE serial RENAME COLUMN "serialNo" TO serial_no;
ALTER TABLE serial RENAME COLUMN "warehouseId" TO warehouse_id;
ALTER TABLE serial RENAME COLUMN "inboundTime" TO inbound_time;
ALTER TABLE serial RENAME COLUMN "outboundTime" TO outbound_time;
ALTER TABLE stock RENAME COLUMN "warehouseId" TO warehouse_id;
ALTER TABLE stock RENAME COLUMN "itemId" TO item_id;
ALTER TABLE stock RENAME COLUMN "batchId" TO batch_id;
ALTER TABLE stock RENAME COLUMN "locationId" TO location_id;
ALTER TABLE stock RENAME COLUMN "updatedAt" TO updated_at;
ALTER TABLE stock RENAME COLUMN "preAllocatedQty" TO pre_allocated_qty;
ALTER TABLE stock_adjust_doc RENAME COLUMN "docNo" TO doc_no;
ALTER TABLE stock_adjust_doc RENAME COLUMN "docDate" TO doc_date;
ALTER TABLE stock_adjust_doc RENAME COLUMN "warehouseId" TO warehouse_id;
ALTER TABLE stock_adjust_doc RENAME COLUMN "adjustType" TO adjust_type;
ALTER TABLE stock_adjust_doc RENAME COLUMN "refDocNo" TO ref_doc_no;
ALTER TABLE stock_adjust_doc RENAME COLUMN "createdAt" TO created_at;
ALTER TABLE stock_adjust_doc RENAME COLUMN "updatedAt" TO updated_at;
ALTER TABLE stock_adjust_doc RENAME COLUMN "approvedAt" TO approved_at;
ALTER TABLE stock_adjust_doc RENAME COLUMN "rejectReason" TO reject_reason;
ALTER TABLE stock_adjust_doc_item RENAME COLUMN "docId" TO doc_id;
ALTER TABLE stock_adjust_doc_item RENAME COLUMN "lineNo" TO line_no;
ALTER TABLE stock_adjust_doc_item RENAME COLUMN "itemId" TO item_id;
ALTER TABLE stock_adjust_doc_item RENAME COLUMN "specSnapshot" TO spec_snapshot;
ALTER TABLE stock_adjust_doc_item RENAME COLUMN "batchId" TO batch_id;
ALTER TABLE stock_adjust_doc_item RENAME COLUMN "locationId" TO location_id;
ALTER TABLE stock_adjust_doc_item RENAME COLUMN "unitPrice" TO unit_price;
ALTER TABLE stock_transaction RENAME COLUMN "warehouseId" TO warehouse_id;
ALTER TABLE stock_transaction RENAME COLUMN "itemId" TO item_id;
ALTER TABLE stock_transaction RENAME COLUMN "batchId" TO batch_id;
ALTER TABLE stock_transaction RENAME COLUMN "locationId" TO location_id;
ALTER TABLE stock_transaction RENAME COLUMN "changeQty" TO change_qty;
ALTER TABLE stock_transaction RENAME COLUMN "afterQty" TO after_qty;
ALTER TABLE stock_transaction RENAME COLUMN "bizCode" TO biz_code;
ALTER TABLE stock_transaction RENAME COLUMN "docNo" TO doc_no;
ALTER TABLE stock_transaction RENAME COLUMN "createdAt" TO created_at;
ALTER TABLE stocktake_doc RENAME COLUMN "docNo" TO doc_no;
ALTER TABLE stocktake_doc RENAME COLUMN "docDate" TO doc_date;
ALTER TABLE stocktake_doc RENAME COLUMN "warehouseId" TO warehouse_id;
ALTER TABLE stocktake_doc RENAME COLUMN "scopeType" TO scope_type;
ALTER TABLE stocktake_doc RENAME COLUMN "createdAt" TO created_at;
ALTER TABLE stocktake_doc RENAME COLUMN "updatedAt" TO updated_at;
ALTER TABLE stocktake_doc RENAME COLUMN "approvedAt" TO approved_at;
ALTER TABLE stocktake_doc RENAME COLUMN "rejectReason" TO reject_reason;
ALTER TABLE stocktake_doc_item RENAME COLUMN "docId" TO doc_id;
ALTER TABLE stocktake_doc_item RENAME COLUMN "lineNo" TO line_no;
ALTER TABLE stocktake_doc_item RENAME COLUMN "itemId" TO item_id;
ALTER TABLE stocktake_doc_item RENAME COLUMN "specSnapshot" TO spec_snapshot;
ALTER TABLE stocktake_doc_item RENAME COLUMN "batchId" TO batch_id;
ALTER TABLE stocktake_doc_item RENAME COLUMN "locationId" TO location_id;
ALTER TABLE stocktake_doc_item RENAME COLUMN "bookQty" TO book_qty;
ALTER TABLE stocktake_doc_item RENAME COLUMN "actualQty" TO actual_qty;
ALTER TABLE stocktake_doc_item RENAME COLUMN "diffQty" TO diff_qty;
ALTER TABLE supplier RENAME COLUMN "supplierCode" TO supplier_code;
ALTER TABLE supplier RENAME COLUMN "supplierName" TO supplier_name;
ALTER TABLE supplier RENAME COLUMN "taxNo" TO tax_no;
ALTER TABLE supplier RENAME COLUMN "defaultTaxRate" TO default_tax_rate;
ALTER TABLE supplier RENAME COLUMN "settleMethod" TO settle_method;
ALTER TABLE supplier RENAME COLUMN "payTermDays" TO pay_term_days;
ALTER TABLE supplier RENAME COLUMN "createdAt" TO created_at;
ALTER TABLE supplier RENAME COLUMN "updatedAt" TO updated_at;
ALTER TABLE transfer_doc RENAME COLUMN "docNo" TO doc_no;
ALTER TABLE transfer_doc RENAME COLUMN "docDate" TO doc_date;
ALTER TABLE transfer_doc RENAME COLUMN "fromWarehouseId" TO from_warehouse_id;
ALTER TABLE transfer_doc RENAME COLUMN "toWarehouseId" TO to_warehouse_id;
ALTER TABLE transfer_doc RENAME COLUMN "totalAmount" TO total_amount;
ALTER TABLE transfer_doc RENAME COLUMN "createdAt" TO created_at;
ALTER TABLE transfer_doc RENAME COLUMN "updatedAt" TO updated_at;
ALTER TABLE transfer_doc RENAME COLUMN "approvedAt" TO approved_at;
ALTER TABLE transfer_doc RENAME COLUMN "rejectReason" TO reject_reason;
ALTER TABLE transfer_doc_item RENAME COLUMN "docId" TO doc_id;
ALTER TABLE transfer_doc_item RENAME COLUMN "lineNo" TO line_no;
ALTER TABLE transfer_doc_item RENAME COLUMN "itemId" TO item_id;
ALTER TABLE transfer_doc_item RENAME COLUMN "specSnapshot" TO spec_snapshot;
ALTER TABLE transfer_doc_item RENAME COLUMN "unitPrice" TO unit_price;
ALTER TABLE transfer_doc_item RENAME COLUMN "fromLocationId" TO from_location_id;
ALTER TABLE transfer_doc_item RENAME COLUMN "toLocationId" TO to_location_id;
ALTER TABLE transfer_doc_item RENAME COLUMN "lineRemark" TO line_remark;
ALTER TABLE sys_user RENAME COLUMN "passwordHash" TO password_hash;
ALTER TABLE sys_user RENAME COLUMN "createdAt" TO created_at;
ALTER TABLE sys_user RENAME COLUMN "updatedAt" TO updated_at;
ALTER TABLE warehouse RENAME COLUMN "warehouseCode" TO warehouse_code;
ALTER TABLE warehouse RENAME COLUMN "warehouseName" TO warehouse_name;
ALTER TABLE warehouse RENAME COLUMN "warehouseType" TO warehouse_type;
ALTER TABLE warehouse RENAME COLUMN "enableBatch" TO enable_batch;
ALTER TABLE warehouse RENAME COLUMN "enableExpiry" TO enable_expiry;
ALTER TABLE warehouse RENAME COLUMN "enableSerial" TO enable_serial;
ALTER TABLE warehouse RENAME COLUMN "enableLocation" TO enable_location;
ALTER TABLE warehouse RENAME COLUMN "createdAt" TO created_at;
ALTER TABLE warehouse RENAME COLUMN "updatedAt" TO updated_at;

COMMIT;
